#include <stdint.h>
#include "video.h"

#define SHIP_W 15
#define SHIP_H 10
#define ALIEN_W 11
#define ALIEN_H 8
#define BULLET_W 3
#define BULLET_H 8

uint8_t ship[SHIP_H*SHIP_W] =
        { VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK,
          VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK,
          VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,
          VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,
          VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL, VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,
          VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL, VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,
          VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL, VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,  VTEAL,
          VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,
          VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,
          VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,  VTEAL, VTEAL,  VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VTEAL,
         };

uint8_t alien[ALIEN_H*ALIEN_W] =
        { VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VBLACK,
          VGREEN, VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VBLACK, VGREEN,
          VGREEN, VBLACK, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VBLACK, VBLACK, VGREEN,
          VGREEN, VGREEN, VGREEN, VBLACK, VGREEN, VGREEN, VBLACK, VGREEN, VGREEN, VGREEN, VGREEN,
          VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN,
          VBLACK, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VGREEN, VBLACK, VBLACK,
          VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VBLACK, VBLACK, VGREEN, VBLACK, VBLACK, VBLACK,
          VBLACK, VGREEN, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VBLACK, VGREEN, VBLACK, VBLACK
         };

uint8_t bullet[8*3] =
        { VBLACK, VWHITE, VBLACK,
          VWHITE, VWHITE, VWHITE,
          VBLACK, VWHITE, VBLACK,
          VBLACK, VWHITE, VBLACK,
          VBLACK, VBLACK, VBLACK,
          VBLACK, VWHITE, VBLACK,
          VBLACK, VBLACK, VBLACK,
          VBLACK, VWHITE, VBLACK
         };